codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...75"

  status:
    project:
      java:
        enabled: yes
        flags: java
        if_not_found: success
      js:
        enabled: yes
        flags: js
        if_not_found: success
    patch: yes
    changes: no
  flags:
    java:
      paths:
        - */src/main/java
    js:
      paths:
        - */src/main/frontend

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no